name = "processgroups"
version = "0.1.3"

description = "Process Groups for gleam"
gleam = ">= 1.1.0"
licences = ["Apache-2.0"]
links = [
  { title = "Gleam", href = "https://gleam.run" },
  { title = "Erlang Process Groups", href = "https://www.erlang.org/doc/man/pg.html" },
]
repository = { type = "github", user = "RudolfVonKrugstein", repo = "gleam_processgroups" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
